schloss:
  enabled: true
  filters:
    exclude_sectors:
    - 银行
    - 保险
    - 证券
    markets:
    - A股
    - US
    - HK
    min_avg_volume: 1000000
    min_trading_days: 250
  name: Walter Schloss Value Strategy
  parameters:
    exclude_financial: true
    exclude_new_listings: true
    max_debt_to_equity: 0.6
    max_pb_ratio: 1.5
    max_pe_ratio: 15
    min_current_ratio: 1.2
    min_listing_years: 3
    min_market_cap: 1000000000
    min_pb_ratio: 0.5
    min_revenue_growth: -0.1
    min_roe: 0.08
  version: 1.0.0
  weight_config:
    growth_score: 0.1
    quality_score: 0.3
    safety_score: 0.2
    value_score: 0.4
