schloss:
  enabled: true
  filters:
    exclude_sectors: []
    markets:
      - A股
      - US
      - HK
  name: schloss
  parameters:
    exclude_financial: false
    exclude_new_listings: false
    max_debt_to_equity: 60
    max_pb_ratio: 1.6
    max_pe_ratio: 18
    min_market_cap: 800000
    min_pb_ratio: 0.3
    min_roe: 8
  version: 1.0.3
  weight_config:
    growth_score: 0.05
    quality_score: 0.3
    safety_score: 0.2
    value_score: 0.45
